### ISSUE TITLE
Change to Talon PIDs for Movement

### ISSUE THREAD

**Issue by eandr127** [FRC2706/2019-2706-Robot-Code#11]
Last year, PIDs built into WPILib were used, but Talon PIDs offer better control.

Integrate auxiliary PID for rotation (might require Pigeon IMU)
Have all movements from last year using Talons

- [x] Drive forward no gyro
- [x] Drive forward with gyro
- [x] Rotate with gyro
- [x] Motion magic drive forward gyro

**Comment by KyleRAnderson** [comment]
I'm currently working on rotate with gyro.

**Comment by eandr127** [comment]
Completed by #57, #70, #75, #76
