### ISSUE TITLE
Investigate Squaring Inputs for Driver

### ISSUE THREAD

**Issue by eandr127** [FRC2706/2019-2706-Robot-Code#134]
This can reduce the sensitivity of the joystick at lower speeds.

**Comment by kevlam2706** [comment]
This currently exists as a parameter to ArcadeDrive but not to CurvatureDrive. Try adding to CurvatureDrive and see if it is helpful.

**Comment by kevlam2706** [comment]
Report from Ryan in testing is that it makes the steering less twitchy, but we'll need Erik to try it out and see if he likes it.

**Comment by KyleRAnderson** [comment]
Pretty sure that this was resolved in #143. @eandr127 can you confirm?

**Comment by eandr127** [comment]
> Pretty sure that this was resolved in #143. @eandr127 can you confirm?

Yes, closed by #143
