### ISSUE TITLE
Investigate involuntary autonomous mode

### ISSUE THREAD

**Issue by kevlam2706** [FRC2706/2019-2706-Robot-Code#150]
At North Bay the robot went crazy in a practice match and started driving in circles. It was reported that the robot was not controllable from the driver joystick. As a workaround, the vision assist commands were disabled.

Investigate the driver assist commands and ensure that they cannot accidentally take over the robot control, i.e. the driver should always be able to cancel the command. If possible, try to reproduce what happened so we know for sure. Test this on all the driver assist commands, including the ones we haven't really been testing with vision (like cargo?)

Finally, as a preventative measure, remove controller bindings for any driver assists that we don't use or aren't ready for use. We'll bring them back in when everyone is happy that they are ready.

**Comment by KyleRAnderson** [comment]
Haven't seen this issue since. We did do some debugging to look to where the cause could have been, but we didn't end up finding a definite source. We have however improved autonomous code since then.
