### ISSUE TITLE
Change bindings so that Interrupt autonomous and vision aren't both bound to the same button

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2019-2706-Robot-Code#152]
Currently, we have the drive assist automatically pick up cargo bound to the same button as the autonomous interrupt. This wasn't supposed to happen. It would make the most sense at this point to move the vision binding to one of the bumpers or triggers since all the other vision commands are there and by now the driver is used to pressing "A" to interrupt.

This is where the problem exists: 

https://github.com/FRC2706/2019-2706-Robot-Code/blob/2e3c087047c60918fc1a6d7bcfe25625a93a416b/src/main/java/ca/team2706/frc/robot/config/Config.java#L247-L272

**Comment by eandr127** [comment]
Completed by #153
