### ISSUE TITLE
Separate class for keeping track of a pneumatic piston

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2019-2706-Robot-Code#159]
In the `modified-climber-testing` branch, I quickly made a `PneumaticPiston` class for more easily controlling pneumatic pistons... and I realized it could be pretty useful to do that for pretty much all of this year's robot's pneumatics.

Having the piston itself deal with determining its current state and how to get to the desired state makes things much cleaner.

Definitely not a priority but something to consider for later.

**Comment by eandr127** [comment]
Closed by #162
