### ISSUE TITLE
Port over autonomous selector logic

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2019-2706-Robot-Code#23]
Every year we have a selector switch for selecting autonomous modes. This year we would like to have it again. The code exists already in the 2018 and the 2017 code repos and can be ported over to this year's repo.

It might be nice to separate the commands from the switch positions themselves.

**Comment by Zinka010** [comment]
Ryan's Spec: Have a class for the selector it self, yet have the logic in a separate file TBD.

**Comment by KyleRAnderson** [comment]
Closed in #44.
