### ISSUE TITLE
Vision integration

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2019-2706-Robot-Code#25]
Would be cool to have a dedicated vision subsystem for integrating the separate vision processor.

This could take the form of a subsystem which calculates the path to be taken for the robot to hit a target and then for the autonomous subsystem to follow this path.

Note that this is simply presenting an idea, may not actually end up making sense to separate the processing like this.

**Comment by eandr127** [comment]
Closed by #160
