### ISSUE TITLE
Config requires initialization in order for FluidConstants to be accessed 

### ISSUE THREAD

**Issue by Zinka010** [FRC2706/2019-2706-Robot-Code#30]

**Comment by KyleRAnderson** [comment]
If I'm understanding this right, you're saying that the FluidConstant outside of the `Config.java` class aren't being initialized? I don't think we want to define FluidConstants outside of the `Config` class.

**Comment by eandr127** [comment]
I agree that they should all be made in `Config`, but I think that they should still work even if they're made in another class or defined after the robot is initialized.

**Comment by KyleRAnderson** [comment]
Ready for testing. Will also need to speak to @Zinka010 to see if this is what the intended behaviour was.
