### ISSUE TITLE
Possible double-initialization of subsystems

### ISSUE THREAD

**Issue by eandr127** [FRC2706/2019-2706-Robot-Code#36]
### Steps to reproduce:
- Get an instance of the subsystem before `robotInit()` finishes (`subsystem.getInstance()`)
  - Will initialize the subsystem if not already done (`subsystem.init()`)
  - Returns the subsystem
- Have `robotInit()` initialize subsystem (`subsystem.init()`)
  - Subsystem will have been initialized twice

**Comment by greyingjay** [comment]
The init() call is public and could be called outside of the getInstance method.
