### ISSUE TITLE
User Input

### ISSUE THREAD

**Issue by carmen1234** [FRC2706/2019-2706-Robot-Code#6]
Use joystick buttons
Outside of code, have bindings (in a JSON file)
Run commands on button press
Look at previous year's code for inspiration

**Comment by KyleRAnderson** [comment]
This is linked to https://github.com/FRC2706/2019-2706-Robot-Code/issues/8 since the configuration for the joysticks (i.e. the button mappings) should be stored in the configuration manager.

**Comment by Zinka010** [comment]
Completed as part of PR #28
