### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by carmen1234** [FRC2706/2019-2706-Robot-Code#7]
Rewrite the logging system
Logging system needs to be able to be fully disabled.
Keep the frontend simple (so that calls to it are easy).
Just need to fix the backend portion of the logging to make it less clunky. 
Maybe have levels of logging so we can disable nuisance logs.
Log to USB
Maybe log to RoboRIO

## Specific Requirements
1. Debug
  - Log to file
    - [x] New log for each instance of application
    - [x] Name includes date/time
    - [x] Rollover that adds indicates the number of the log for that application
  - Log to console
    - [x] Standard Out
2. Info
  - Log to file
  - Log to console
3. Warning
  - Log to file
  - Log to console
  - Log to driver station
    - [x] Driverstation.reportWarning()
4. Error+
  - Log to file
  - Log to console
    - [x] Standard Error
  - Log to driver station
    - [x] Driverstation.reportError()
5. Wrapper
  - [x] Disable logging
  - [x] Wrappers for logs
6. Async logger

**Comment by eandr127** [comment]
Another place that we may want to log to is the driver station for warnings and errors

**Comment by KyleRAnderson** [comment]
Spec as required from the document: 
> Logging for sensors, results, voltages, current, and statements
